version: '2'
services:
  bcnbalance:
    image: lykkex/bcnbalance:dev
    container_name: bcnbalance
    environment:
      - SettingsUrl=${SettingsUrl}
    ports:
      - "5000:5000"
    networks:
      mynet:
        aliases:
          - bcnbalance
   

networks:
  mynet:
    driver: bridge
